ogma-cli: Disable secure mode for package repo in Cabal config in CI jobs. Refs #537.
CI jobs are failing frequently with 404 errors. The errors are not
consistent and are hard to reproduce, and manifest as AWS Hackage
mirrors that fail to respond:

> Unexpected response 404for http://objects-us-east-1.dream.io/hackage-mirror/package/StateVar-1.2.2.tar.gz
>
> Error: Process completed with exit code 1.

Errors seem to happen more often, if not exclusively, in CI workflows
that use older versions of Cabal. Attempts at rebuilding in CI
eventually succeed, but can sometimes take tens of tries, which also
take an unpredictable amount of time.

This commit modifies the CI workflow files to disable secure mode for
the Hackage package repository in Cabal's configuration file, and later
updates the list of packages available. Disabling secure mode allows
Cabal to download packages from different mirrors even when the server's
root keys do not match what Cabal expects.